# Generated by Django 4.0.4 on 2022-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='idProducto')),
                ('NombreProducto', models.CharField(max_length=200, verbose_name='NombreProducto')),
                ('CategoriaProducto', models.CharField(max_length=200, verbose_name='CategoriaProducto')),
                ('Precio', models.IntegerField(verbose_name='Precio')),
                ('Stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
    ]
