# Generated by Django 4.0.4 on 2022-06-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto1',
            fields=[
                ('idProducto1', models.IntegerField(primary_key=True, serialize=False, verbose_name='idProducto')),
                ('NombreProducto1', models.CharField(max_length=200, verbose_name='NombreProducto')),
                ('CategoriaProducto1', models.CharField(max_length=200, verbose_name='CategoriaProducto')),
                ('Precio1', models.IntegerField(verbose_name='Precio')),
                ('Stock1', models.IntegerField(verbose_name='Stock')),
            ],
        ),
    ]
