# Generated by Django 4.0.4 on 2022-06-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto1',
        ),
    ]
